---

pool:
  vmImage: 'ubuntu-latest'

trigger:
- master

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash

      # Get disk utilization
      disk_utilization=$(df -h / | awk '{ print $5 }' | tail -n 1 | cut -d'%' -f1)

      # Print disk utilization
      echo "Disk utilization: $disk_utilization%"