---
pool
  name: "Azure Pipelines"
  vmImage: ubuntu-latest
  
trigger:
  - main
  
steps:
  - task: Maven@4
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'package'
      jdkVersionOption: '1.17'