---
pool:
  name: default

trigger:
  - main


steps:
  - task: Maven@3
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'package' 
      publishJUnitResults: yes
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkVersionOption: '1.17'
      jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64
      mavenVersionOption: 'Path'
      mavenDirectory: /home/AseeDevops/apache-maven-3.9.0
