---
pool:
  name: default
  vmImage: 'ubuntu-20.04'

trigger:
  - master

steps:
  - script: 'docker compose -f local.yml run --rm django coverage run -m pytest --junitxml=/app/Test-pytest.xml'
    continueOnError: true
  
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
